<?php
//Thanks to David Perez y Herduin
$labels = array();
$labels['shownotifies'] = 'Notificaciones  de Escritorio';
$labels['conf_browser'] = 'Configurar Navegador';
$labels['test_browser'] = 'Probar';
$labels['excluded_directories'] = 'Directorios excluidos de notificaciones';
$labels['check_ok'] = 'La configuración de tu navegador es correcta.';
$labels['check_fail'] = 'No fue posible mostrar la notificación, por favor haz clic en "Configurar Navegador"!';
$labels['check_fail_blocked'] = 'Notificaciones bloqueadas, por favor revise la configuracion de su navegador.';
$labels['no_notifications'] = 'Su navegador no permite notificaciones!';
$labels['ok_notifications'] = 'Esta web ya tiene permiso. Las notificaciones de Escritorio deberían de estar funcionando.';
$labels['notification_title'] = 'Nuevo Email de [from]';

$labels['seconds'] = 'segundos';
$labels['off'] = 'desactivado';
$labels['durable'] = 'durable';

$labels['no_mailbox'] = 'no mostrar bandeja';
$labels['short_mailbox'] = 'mostrar un extracto de bandeja';
$labels['full_mailbox'] = 'mostrar toda la bandeja';
?>
